### ISSUE TITLE
Stop Activity ?

### ISSUE THREAD

**Issue by Ludwig151** [i8beef/HarmonyHub#10]
Hello,
First, Thanks for this fabulous tool !!
I've found the command to start an activity on my harmony hub but I've not found the command to stop the current running activity...
No StopActivity Command ????
So, how can I do ?
Thanks
Have a nice day

**Comment by i8beef** [comment]
Just start the "PowerOff" activity. Think of it as a "toggle" instead of a distinct start / stop.
