### ISSUE TITLE
command is only send with status:press

### ISSUE THREAD

**Issue by WueBumbum** [i8beef/HarmonyHub#7]
Hello,

I just tried this nice tool. But I have problems. I want to send a single IR command. If I use the SendCommandAsync method, the IR command is sent twice.

I think I found the reason: It is only send the command with status=press to the hub, not status:release.

I think it has to be done like this:

{"command":"TestL01","type":"IRCommand","deviceId":"???"}:status=press:timestamp=0
{"command":"TestL01","type":"IRCommand","deviceId":"???"}:status=release:timestamp=55

Can this be added? The best will be configurable (on and off the release and configurable delay beetwen the time-stamps) to stay compatible  with older versions.

best regards,
Bumbum

**Comment by i8beef** [comment]
That's correct, I only send the one command. I will look around at how some others do this. I haven't personally had an issue with this, but then I haven't tried hitting anything that might have a ramping effect like volume or channel up and down. I'll look it over this weekend.

**Comment by WueBumbum** [comment]
Hello Michael,
 
thank you for your effort. I think the best will be to add 2 optional parameters to the SendCommandAsync method: The first should be an optional enum with the possibilites (pressonly, releaseonly, timespan). Default should be pressonly and it does exactly the same as at the moment. So it will be downwards compatible. realesonly the sam, just changed with status=realase and timespan like my example with two commands (press and relaese) and the timestamp calculated on the secons optional parameter for SendCommandAsync.
 
I believe with this option all eventuantualities should be covered.
 
best regards,
Andreas
 



Am 17.10.17 um 21:22 schrieb Michael Hallock

**Comment by i8beef** [comment]
I think I finally have a device that might exhibit the same behavior. I'll look at adding this in this weekend finally now that I have something to reproduce with.
